### ISSUE TITLE
left right flipped on some 850C display hardware

### ISSUE THREAD

**Issue by geeksville** [OpenSource-EBike-firmware/Color_LCD#10]
(forking from the whitescreen bug).  Apparently some 850C hardware has left and right swapped on  the screen.

Alas, I don't have one of these units to test with.  But I bet they just stuffed a display board from a different vendor.  And the 'quick' fix is to change the 0x0a to 0x08 on this line:

https://github.com/geeksville/Color_LCD/blob/465f91a72ef43ecfb902848de7e4566fd32942af/firmware/850C/src/ugui_driver/ugui_bafang_850c.c#L205 

If a user can confirm this fixes the swapping for them, then the clean fix is one of two things:

a) (easier) add a settings option to 'flip screen horizontal' and based on that setting use the correct value.  It would mean that some users would initially boot and see their screen swapped and have to look at it in a mirror (or just be clever) until they can get into our settings menu and change that value.

b) (slicker but a fair amount of work) - I bet the mfg is using the NVRAM in the display board to mark which type of display they are using and recent versions of their firmware are checking this.  We'd need to add code to also read that NVRAM data, ask a user with an effected device to to run it and tell us what we printed.  I bet we find that comparing that value to a display that doesn't need a flip shows a different value.  Based on that information we could have our firmware make the same decision on when to flip: https://github.com/geeksville/Color_LCD/blob/465f91a72ef43ecfb902848de7e4566fd32942af/firmware/850C/src/ugui_driver/ugui_bafang_850c.c#L220-L222

**Comment by geeksville** [comment]
@r0mko what did your unit print for the display driver part #?  I think that with that info we can have properly flip the X direction as needed (so the same load works on both new and old devices)

**Comment by r0mko** [comment]
> @r0mko what did your unit print for the display driver part #? I think that with that info we can have properly flip the X direction as needed (so the same load works on both new and old devices)

it prints 0000 0000 0000 0000 0000 0000
![image](https://user-images.githubusercontent.com/14110616/65175003-4d443580-da52-11e9-916b-0d79711529a1.png)
