### ISSUE TITLE
Empty display if i click on the M-button

### ISSUE THREAD

**Issue by Ederborg** [OpenSource-EBike-firmware/Color_LCD#17]
If i start the device (sw102) an click on the m-button and release it all fields on the main display lose their data. If i rotate the bicycle wheel or change assist level those fields start showing numbers again.

https://youtu.be/QdEn_c6jqHs

**Comment by geeksville** [comment]
Will fix in 0.19.18.  We need to force a screen redraw on M release, if we've been "force labelling" fields.
