### ISSUE TITLE
SW102 wiring error in wiki?

### ISSUE THREAD

**Issue by geeksville** [OpenSource-EBike-firmware/Color_LCD#2]
Hi @casainho 

Is your LCD SW102 cable also wired this way?

https://github.com/OpenSource-EBike-firmware/Color_LCD/wiki/Bafang-LCD-SW102#Eletric_signals
Green - UART TX
Black - UART RX
Red - GND
Blue - LOCK
Yellow - BAT+

The reason I ask is that I just double checked against the connector I cut off of mine and it seems to me that the colors in my cable match the convention used on the LCD3:
Red from bat
Blue control to motor (same as above)
Green tx data (same as above)
Yellow rx data
Blk gnd

I'm worried that if I hook up my SW102 incorrectly I might let a bit of the smoke out.

**Comment by casainho** [comment]
No, I just checked again. And Nick, the other developer, also updated that wiki page. Here I picture I took just now for you to see:

![image](https://user-images.githubusercontent.com/147128/61775905-cb3ce500-adf1-11e9-95ea-56be79ffef9f.png)

**Comment by geeksville** [comment]
yep - wiki was right. ;-).  I was too paranoid.
