### ISSUE TITLE
850C might not be packing eeprom contents as expected

### ISSUE THREAD

**Issue by geeksville** [OpenSource-EBike-firmware/Color_LCD#3]
Hi,

While mergemotizing the 850C eeprom code into SW102 (and slightly refactoring) I noticed a funny thing.  On line 17 of eeprom.c it says:

// to make structures use only bytes and have no paddings
#pragma pack(1)

I don't think this is doing what you expect.  Because by the time that pragma is encountered - the key structure (eeprom_data_t) has already been defined in the .h file.   I think the pack needs to be in the .h file before the structure def (and put pragma pack() afterwards to not mess up other structures).  (Or use the gcc __attribute__((packed,aligned(1)))

**Comment by casainho** [comment]
Thanks!!!
