### ISSUE TITLE
850C: Small error in Makefile

### ISSUE THREAD

**Issue by xvlvx0** [OpenSource-EBike-firmware/Color_LCD#31]
I'm not sure what the influence is, but I just want to remark that in the Makefile: ("Color_LCD/firmware/850C/src/") on line: 54 is a small typo error.
`CFLAGS+ = -fno-builtin`

I think it should be:
`CFLAGS += -fno-builtin`

regards,
xvlvx0

**Comment by casainho** [comment]
Thanks. Corrected this just now.
