### ISSUE TITLE
Display Infoscreen the .div_digits  funktion works not (seen on sw102, but also would be in 850c)

### ISSUE THREAD

**Issue by StefanKie** [OpenSource-EBike-firmware/Color_LCD#32]
Hello
the .div_digits = 1 works on Infoscreen not 
odo display 123 means 12,3 km

@geeksville 
I have some funtions built in, for example
Watts per km,
Battery range km,
Average speed,
Time in actual driving time,
new display layout
I would like to send it to you so you can install it if you like it

**Comment by StefanKie** [comment]
ps the Average speed,
Time in actual driving time (trip time) and
trip distance are saved in eprom 
it can clear with long press M key

**Comment by geeksville** [comment]
Hi Stephan,

Alas I'm severely afk right now but when I return to my computer Nov 5th
I'll look into this promptly. 😍

(Sent from a phone - please ignore typos)

**Comment by casainho** [comment]
Solved on last version.
