### ISSUE TITLE
GUI issues with 0.19.17

### ISSUE THREAD

**Issue by lowPerformer** [OpenSource-EBike-firmware/Color_LCD#33]
I see some issues with current beta version of SW102 firmware:

+ To be honest, I really don't like the "feeling" of the buttons. They are not very snappy and are lagging. Sometimes (quite often) clicks don't get recognized at all and sometimes they are doubled. For me this is frustrating and imho we should optimize this in future releases! I come from pre-merge version and there the button feeling was good.

+ When I leave a menu to the root settings page, sometimes up/down buttons do not work any more. I have to quit to main menu and enter again then.

+ The offset of the marker arrow is a bit confusing (I know, we need the space) but that is sure a matter of taste. I liked the underscore more.

+ Sometimes if you navigate down, the old arrow position is not cleared and you have one solid and one blinking arrow then:
![IMG_20191020_124641_1](https://user-images.githubusercontent.com/49353266/67158668-5a975d00-f33b-11e9-95f1-f6b86208308a.jpg)

+ Unit gets overwritten by speed value:
![IMG_20191020_130332](https://user-images.githubusercontent.com/49353266/67158598-6f272580-f33a-11e9-9c26-05f6ce19f73f.jpg)

Greetings
Niklas

@casainho @geeksville

**Comment by geeksville** [comment]
these issues are not sw102 specific, so editing title for clarity.

**Comment by geeksville** [comment]
@lowPerformer  btw - I just fixed the "arrow turd left on the screen bug" - I'll look into the others later (after doing the software update without solder thing).  Thanks for the report.  (or if you wanna send in a PR that would be great also?  but no pressure)

**Comment by lowPerformer** [comment]
Sorry, no PR. Just complaining ;)

**Comment by geeksville** [comment]
complaining is useful also ;-)
