### ISSUE TITLE
850C eeprom code overrwriting memory

### ISSUE THREAD

**Issue by geeksville** [OpenSource-EBike-firmware/Color_LCD#4]
Hi @casainho,
While testing the SW102 based code I noticed an error inherited from the 850C code.

The following code in eeprom.c is reading past the end of a 9 element array:
  p_l3_output_vars->ui8_walk_assist_level_factor[9] = m_eeprom_data.ui8_walk_assist_level_factor[9];

**Comment by geeksville** [comment]
(for the sw102 fork I changed the eeprom array size to 10)

**Comment by casainho** [comment]
Thanks!!
