### ISSUE TITLE
Release 850C_v0.5.0-beta.5:  Imperial setting not working

### ISSUE THREAD

**Issue by mikecy1953** [OpenSource-EBike-firmware/Color_LCD#42]
Set display units to 'Imperial'.   Main screen says MPH but actual speed and Trip reading showing up in KM/h.   Problem also existed with Release 850C_v0.5.0-beta.4.

**Comment by eyebyesickle** [comment]
Yes, it seems the ODOMETER IS reading in MPH when set to imperial, but the SPEEDOMETER AND TRIP ARE NOT reading in MPH - they are still KPH... this is still a problem with the newest version I beleive

**Comment by eyebyesickle** [comment]
whoops, looks like you just fixed this

**Comment by casainho** [comment]
should be fixed on next release.
