### ISSUE TITLE
Experimental High RPM mode very glitchy, won't put out more than 200wish

### ISSUE THREAD

**Issue by eyebyesickle** [OpenSource-EBike-firmware/Color_LCD#52]
Experimental High RPM mode very glitchy, won't put out more than 200wish

At super low power it seemed to work a little, but it is very glitchy, and with any higher assist it makes very bad sounds, and is un-useable

**Comment by eyebyesickle** [comment]
I am not sure if this is due to the Display firmware, or if this is a Motor firmware issue, and should be addressed there - apologies if this is in the wrong spot

**Comment by casainho** [comment]
Solved on last version.
