### ISSUE TITLE
850C_v0.5.0-beta.7 Configuration Menus

### ISSUE THREAD

**Issue by mikecy1953** [OpenSource-EBike-firmware/Color_LCD#54]
Method for entering Configuration Menu from Main Screen not reliable.  Had to repeat steps at least 10 times before it worked.

**Comment by redwater32** [comment]
When I press up (+) and down (-) it works like short and long press power button, configuration menu not apears.

**Comment by casainho** [comment]
> Method for entering Configuration Menu from Main Screen not reliable. Had to repeat steps at least 10 times before it worked.

Please explain how did you do it and what do you think why is not working.

**Comment by mikecy1953** [comment]
First I tried this method that you posted on Endless-Sphere.   I was never able to get this to work. 
"- UP and DOWN click to enter configurations screen"

Next I tried this method that was posted on the github site.  I was able to get it to work after numerous tries.   More often than not it would take me to the subfields on the main screen.
"To enter the configuration menu: long press the UP and DOWN buttons"

**Comment by mikecy1953** [comment]
When I tried to use this method this morning "ON/OFF quick click + long press to enter configurations screen" I could not enter the configuration menus at all.  Tried about 20 times and gave up.   All that happens is my display turns off.

**Comment by casainho** [comment]
Solved on last version.
