### ISSUE TITLE
Throttle Jerky/Not Variable (may be motor firmware, and not LCD?)

### ISSUE THREAD

**Issue by eyebyesickle** [OpenSource-EBike-firmware/Color_LCD#60]
Here are two videos to show the issue

Stock Firmware Throttle - Smooth and Variable:
https://drive.google.com/file/d/1bGJIJ1IkRpDSuatzr2qpJjbZGnofGHCd/view?usp=sharing

OSF Throttle - Jerky and Not Variable:
https://drive.google.com/file/d/1bCfWXCv9ASZVB4TYPaGChmlU3UXJ37va/view?usp=sharing

**Comment by eyebyesickle** [comment]
not sure what happened to the video format, but you should still be able to see the issue. also, sorry for the clanking - loose hardware

**Comment by casainho** [comment]
The thing is that I am the only developer right now and I do not use throttle so I can´t develop and test it. Let´s hope other developers join and want to solve this issue.

Thanks for the detailed reporting.

**Comment by eyebyesickle** [comment]
No problem. Yes, I do not use it either, I prefer the temp sensor and max power, if I want a throttle, I would use a BBSHD or other motor, but just passing along feedback.

Thanks

**Comment by muppettMP** [comment]
I think this is normal, becouse in OSF throttle is in current/power control mode so if you put Your motor under load You will have normal/variable throttle.

When You are testing motor on your bench there is 0 load and it causes problems.

**Comment by casainho** [comment]
> I think this is normal, becouse in OSF throttle is in current/power control mode so if you put Your motor under load You will have normal/variable throttle.
> 
> When You are testing motor on your bench there is 0 load and it causes problems.

Makes sense. It would need to be current/power control + speed control.

**Comment by eyebyesickle** [comment]
I have had this reports from other users who state throttle is not operating properly when installed... i was just trying to show a visual example. it does have some slight element of variability, but it really suffers alot compared to stock, which has been reported to me by several users...

**Comment by eyebyesickle** [comment]
when you increased the resolution this solved the problem...it was variable LOW power that was the real issue!
