### ISSUE TITLE
add a "auto calibrate milliohm mode" 

### ISSUE THREAD

**Issue by geeksville** [OpenSource-EBike-firmware/Color_LCD#7]
The SOC calcs on my bike seem far off, I guess because I haven't yet calibrated the milliohm resistance of the pack.  The docs say do a ride with power output pegged at 10A draw and then do some math.

Now that we have displays with more flexibility than the KT-LCD3 it would be great to have a "autocal mode" where it configs the bike with these limits, and as long as user keeps pedaling for 10 secs (or whatever) and the power stayed good the whole time it would then pop up a dialog saying "auto cal successful" and set the milliohm level in the EEPROM.

Adding this idea to do someday...

**Comment by casainho** [comment]
Like, show to user: start calibrating process, drive with motor max current. Display records on next 10 seconds max current value and voltage at that moment and shows in real time to user the resistance value. At the end of the process, record automatically the value.

**Comment by casainho** [comment]
I think we should give information to user also so he can validate and learn, for me, this project is also about education the user and I think it is strategic, is not only firmware, it is knowledge!!

**Comment by geeksville** [comment]
Good point!

(Sent from a phone - please ignore typos)

**Comment by casainho** [comment]
Implemented on last version.
