### ISSUE TITLE
SW_102 reinstall 0.19

### ISSUE THREAD

**Issue by giannidip** [OpenSource-EBike-firmware/Color_LCD#78]
SW012 - after you install version 0.65,  OTA installation in dfu of 0.19.12 fails.

**Comment by wildekek** [comment]
You can't roll back to previous versions until we make a new bootloader. https://github.com/OpenSource-EBike-firmware/Color_LCD/issues/68

**Comment by casainho** [comment]
Only option is to use latest version anyway.
