### ISSUE TITLE
[850C v0.6.8] Runaway throttle issue

### ISSUE THREAD

**Issue by jnkr1** [OpenSource-EBike-firmware/Color_LCD#82]
after a flash, and setting my configs i went to press gently on the throttle and had the bike lurch and run away from me.

the throttle exhibits strange behavior when you first enable it. however, when you enable the throttle and restart the unit, it seems fine (i havent taken it on the road test).

all this is testing after having just enabled the throttle and before any power cycles: just now i had the bike lurch exiting the config after enabling the throttle. also the throttle seems very powerful, it seems more gentle after the power cycle.

**Comment by JamesBroadhurst** [comment]
This has been present for a very long time - a year at least. Although Casainho has said there is no difference in the treatment of the throttle between the original firmware and the OS firmware, the OS throttle if there is no weight on the bike, ie you, will if applied run away. When there is some weight on the bike, it behaves normally. The original firmware had better control of it. The other issue with the throttle is that the spring return is mechanically pretty crap and sticks such that once on the throttle can stay on. Basically the throttle was pretty useless and I only ever used it for initial testing of the motor until walk mode was found to be an adequate test and the temperature control was far more useful.
