### ISSUE TITLE
850C v6.9 does not work with Motor v5.5

### ISSUE THREAD

**Issue by eyebyesickle** [OpenSource-EBike-firmware/Color_LCD#85]
850c 6.9 gives 'firmware error, code upon startup, will not load. Reverted to 6.8 and it started right up.

 Confirmed on 2 separate units

**Comment by mrfusi0n** [comment]
Confirmed as well

**Comment by casainho** [comment]
I updated all the firmware files and I hope it is ok now. The firmware is expecting TSDZ2 firmware 0.55.x.
