### ISSUE TITLE
Request: watt hours / KM display

### ISSUE THREAD

**Issue by JonasCz** [OpenSource-EBike-firmware/Color_LCD#91]
One particular feature I'd love to have would be to be able to see watt hours per km (mile) on the display. Seems like just dividing the power by the speed might be enough - but it would be even awesomer if it could calculate and display an average over some specific amount of time - (seconds, minuites..?)

Handy to be able to see at a glance what speed, gear, cadence, etc is most efficient. Also cool for people experimenting with solar charging, or just having an idea of how far I'll be able to go given that I know my battery capacity.

Thanks for making this awesomely amazing firmware!

**Comment by casainho** [comment]
Watt hours per km will also change depending of amount of current pulled from the battery due e to losses on internal battery resistance that is now measured automatically by the display.

Also I hope to implement the field weakening for having motor assisting over the 90 RPM cadence and there the current can double for having the same torque, so, highly no linear... so, this Watt hours per km is really important!!

I would like to accept a pull request with this feature!!

**Comment by casainho** [comment]
Implemented on last version.
